apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      volumes:
        - name: data
          hostPath:
            path: /disk1/neo4j
            type: DirectoryOrCreate
        - name: neo4j-conf
          configMap:
            name: neo4j-conf
            items:
              - key: neo4j.conf
                path: neo4j.conf
      containers:
      - name: neo4j
        image: neo4j
        ports:
          - containerPort: 7474
          - containerPort: 3000
          - containerPort: 7687

        volumeMounts:
          - mountPath: /data
            name: data

          - name: neo4j-conf
            mountPath: /var/lib/neo4j/conf/neo4j.conf
            subPath: neo4j.conf
