apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  type: NodePort
  ports:
    - protocol: TCP
      name: "7474"
      port: 7474

    - protocol: TCP
      name: "7687"
      port: 7687
