apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgraph
  labels:
    app: memgraph
spec:
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      labels:
        app: memgraph
    spec:
      volumes:
        - name: data
          hostPath:
            path: /disk1/memgraph
            type: DirectoryOrCreate
      containers:
      - name: memgraph
        image: memgraph/memgraph-platform:latest
        ports:
          - containerPort: 7474
          - containerPort: 3000
          - containerPort: 7687
        volumeMounts:
          - mountPath: /var/lib/memgraph/
            name: data
