---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redeye
replicas:
  - name: redeye
    count: 1
resources:
  - ssh://git@github.com/oonray/HackTheBox.git/base/redeye
  - secrets.enc.json
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
