apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: data
          hostPath:
            path: /disk1/postgres
            type: DirectoryOrCreate
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-pass
                key: passwd
        volumeMounts:
          - mountPath: /data/db
            name: data
